layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  twitter: danigonlinea
  medium: danigonlinea
  stackoverflow: danigonlinea
  linkedin: daniel-gonzalez-jimenez
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:

  - name: HTML
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/HTML5_logo_resized.svg/424px-HTML5_logo_resized.svg.png

  - name: Javascript
    image_url: https://f1.pngfuel.com/png/951/574/485/react-logo-javascript-redux-vuejs-angular-angularjs-expressjs-front-and-back-ends-png-clip-art.png

  - name: CSS
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: React
    image_url: https://img.stackshare.io/service/1020/OYIaJ1KK.png

  - name: Redux
    image_url: https://raw.githubusercontent.com/reduxjs/redux/master/logo/logo.png

  - name: Expo (React Native)
    image_url: https://static.expo.dev/static/brand/square-512x512.png

theme: jekyll-theme-cayman